name: Build and Push Docker Image for API

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    env:
      working-directory: ./

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and tag Docker image # Dockerイメージをビルドしてタグをつける
      uses: docker/build-push-action@v2
      with:
        context: ${{env.working-directory}}
        push: false # 一時的にプッシュしない
        tags: |
          come25136/scper-api:latest
          come25136/scper-api:${{ github.sha }}

    - name: Push Docker image to Docker Hub # DockerイメージをDocker Hubにプッシュ
      if: github.ref == 'refs/heads/main' # mainブランチにコミットされた場合のみ実行する
      uses: docker/build-push-action@v2
      with:
        context: ${{env.working-directory}}
        push: true # プッシュを許可する
        repository: come25136/scper-api
        tags: |
          come25136/scper-api:latest
          come25136/scper-api:${{ github.sha }}
